services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db

  db:
    container_name: postgres_container
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pg_banners
      POSTGRES_INITDB_SCRIPT: /docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  tests:
    build: .
    depends_on:
      - db
    command: go test -v
    networks:
      - backend

networks:
  backend:
    driver: bridge
